name: CI
run-name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
          npm install
          npx expo install jest-expo jest
    - name: Run tests
      run: npm test